
version: '3.8'
services:

  cli:
    image:    mongo:3.0
    command:  /bin/bash 
    working_dir: /root    
    volumes:
      - .:/root
      
          
  configserver:
    image:    mongo:3.0
    container_name: configserver
    command:  mongod --configsvr


  queryrouter:
    image:    mongo:3.0
    container_name: "queryrouter.docker"
    command:  mongos --configdb configserver
    depends_on: 
      - configserver

        
  shard1:
    image:    mongo:3.0
    container_name: "shard1.docker"
    command:  mongod --shardsvr --port 27017 --nojournal


  shard2:
    image:    mongo:3.0
    container_name: "shard2.docker"
    command:  mongod --shardsvr --port 27017 --nojournal


  shard3:
    image:    mongo:3.0
    container_name: "shard3.docker"
    command:  mongod --shardsvr --port 27017 --nojournal


  jupyter:
    build:    .
    image:    my-jupyter
    command:  start-notebook.sh --NotebookApp.token='' --NotebookApp.base_url=/ --ip=*
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan
    
    
    
